project:
  type: website
  output-dir: docs

website:
  title: "Основы геоинформатики"
  navbar:
    left:
      - href: index.qmd
        text: Лекции
      - href: https://aentin.github.io/qgis-course/
        text: Практикум в QGIS
      - href: https://tsamsonov.github.io/arcgis-course/
        text: Практикум в ArcGIS

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

