project:
  type: website
  output-dir: docs

website:
  title: "Основы геоинформатики"
  page-footer: |
        © 2023, Тимофей Самсонов, Географический факультет МГУ имени М. В. Ломоносова
  navbar:
    left:
      - href: index.qmd
        text: Лекции
      - href: https://aentin.github.io/qgis-course/
        text: Практикум в QGIS
      - href: https://tsamsonov.github.io/arcgis-course/
        text: Практикум в ArcGIS
    right: 
      - href: https://instagram.com/gis_in_pictures?igshid=NDk5N2NlZjQ=
        icon: instagram

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

lang: ru

