project:
  type: website

website:
  title: "Основы геоинформатики"
  navbar:
    left:
      - href: index.qmd
        text: Лекции
      - exercises.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

