---
title: "Координатные системы отсчета"
subtitle: "Геоинформатика I. Базы пространственных данных"
date: today
date-format: long
author: "Самсонов Тимофей Евгеньевич"
execute:
  echo: false
  freeze: true
engine: knitr
format:
  revealjs: 
    theme: [default, custom.scss]
    margin: 0.2
    width: 1280
    height: 720
    slide-number: true
    footer: "Самсонов Т. Е. Геоинформатика: курс лекций"
    header-includes: <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/pt-sans" type="text/css"/>
bibliography: references.yaml
mainfont: PT Sans
---

## Координатная система отсчета

```{mermaid}
%%| fig-width: 12
flowchart LR
  A(Система отсчета) --> B(Пространственная)
  A --> C(Временная)
  B --> D(Географические идентификаторы)
  B --> E(Координатная)
  B --> F(Параметрическая координатная)
  C --> G(Координатная)
  C --> H(Порядковая)
  C --> I(Календари)
  E --> J(Координатная)
  F --> J
  G --> J
```

## Определение SRS на языке WKT

**WKT** представляет одну систему координат или объект координатной операции.

-   Каждый объект представляется в виде токена, состоящего из ключевого слова, за которым следует множесто атрибутов объекта.

-   Некоторые объекты состоят из других объектов, поэтому результат может состоять из нескольких уровней вложенности (глубина не ограничена).

Пример для трёх уровней:

``` code
KEYWORD1[
  attribute1, 
  KEYWORD2[
    attribute2, 
    attribute3,
    KEYWORD3[
      attribute4
    ]
  ]
]
```

## Общие атрибуты

Вне зависимости от типа описываемого объекта ему всегда могут быть заданы:

1.  Имя (*name*).

2.  Использование (*usage*)

    -   Область применения (*scope*).

    -   Пространственный охват (*extent*).

3.  Идентификатор (*identifier*).

4.  Ремарка (*remark*).

::: callout-note
## Имя

Имя является обязательным атрибутом при описании *координатной системы отсчета*, а также для некоторых компонент структуры ее описания
:::

## Использование

`<usage>` включает в себя обязательную пару области применения и охвата:

`USAGE[<scope>, <extent>]`

`<scope>` представляет текстовое описание области применения:

`SCOPE["Engineering survey, topographic mapping."]`

`<extent>` хранит описание пространственного охвата:

-   `AREA["Between 36°E and 42°E, northern hemisphere]`

-   `BBOX[0, 36, 84, 42]` --- $[\phi_0, \lambda_0, \phi_1, \lambda_1]$

-   `VERTICALEXTENT[-1000,0]`

-   `VERTICALEXTENT[-200, 6000, LENGTHUNIT["metre",1.0]]`

-   `TIMEEXTENT[2013-01-01,2013-12-31]` --- $[T_0, T_1]$

-   `TIMEEXTENT["Carbon", "Pleistocene"]`

Токенов `<usage>` может быть несколько --- для каждой области применения.

## Примеры

**UTM 37N**

``` code
USAGE[
  SCOPE["Engineering survey, topographic mapping."],
  AREA["Between 36°E and 42°E, northern hemisphere between equator 
        and 84°N, onshore and offshore. Djibouti. Egypt. Eritrea. 
        Ethiopia. Georgia. Iraq. Jordan. Kenya. Lebanon. Russian 
        Federation. Saudi Arabia. Somalia. Sudan. Syria. Turkey. 
        Ukraine."],
  BBOX[0,36,84,42]]
```

**Местная система координат**

``` code
USAGE[
  SCOPE["Small scale topographic mapping."], 
  AREA["Finland - onshore and offshore."]],
USAGE[
  SCOPE["Cadastre."],
  AREA["Finland - onshore between 26°30'E and 27°30'E."], 
  BBOX[60.36,26.5,70.05,27.5]]
```

## Идентификатор

**Идентификатор** --- опциональный (необязательный) атрибут, который представляет ссылку на внешнее описание объекта (координатной системы, операции и т.д.).

+-------------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `<wkt separator>` | `::=` | `<comma>`                                                                                                                                                                                                                    |
+-------------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `<identifier>`    | `::=` | `<identifier keyword> <left delimiter> <authority name> <wkt separator> <authority unique identifier> { <wkt separator> <version> } { <wkt separator> <authority citation> } { <wkt separator> <id uri> } <right delimiter>` |
+-------------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

``` code
ID["Росреестр", "СК-ХХХ", 666]
ID["EPSG",20907]  — GSK-2011 / Gauss-Kruger zone 23
ID["EPSG",4326,URI["urn:ogc:def:crs:EPSG::4326"]]
ID["ESRI",102604] — NAD_1983_Georgia_Statewide_Lambert
```

## Ремарка (примечание)

**Ремарка** является опциональным параметром и носит информационный характер, т.е. не влияет на поведение объекта, к которому она относится.

-   Ремарки нельзя использовать на уровне компонент координатной системы.

-   Ремарка --- единственное место в WKT, где можно использовать символы, не входящие в латинский алфавит.

``` code
GEOGCRS["S-95",
  DATUM["Pulkovo 1995", 
    ELLIPSOID["Krassowsky 1940",6378245,298.3, LENGTHUNIT["metre",1.0]] ], 
  CS[ellipsoidal,2], 
    AXIS["latitude",north,ORDER[1]], 
    AXIS["longitude",east,ORDER[2]], 
    ANGLEUNIT["degree",0.0174532925199433], 
  REMARK["Система Геодеэических Координат года 1995(СК-95)"]
]
```

## Единицы измерения

**Единицы измерения** указываются для некоторых параметров осей координат, а также параметров координатных операций.

+------------------+------------+-------------------------------------------------------------------+
| `<spatial unit>` | `::=`      | `<angle unit> | <length unit> | <parametric unit> | <scale unit>` |
+------------------+------------+-------------------------------------------------------------------+
| `<unit>`         | `::=`      | `<spatial unit> | <time unit>`                                    |
+------------------+------------+-------------------------------------------------------------------+

После единицы измерения указывается *коэффициент пересчета:*

``` code
LENGTHUNIT["metre",1] 
LENGTHUNIT["German legal metre",1.0000135965] 
ANGLEUNIT["degree",0.0174532925199433] 
SCALEUNIT["parts per million",1E-06] 
PARAMETRICUNIT["hectopascal",100]
```

::: callout-important
## Эталоны

Коэффициенты пересчета указываются ***к*** эталонным единицам СИ: метрам, радианам и т.д.
:::

## Система координат

Определяется рядом параметров:

+-----------------------+-------------+--------------------------------------------------------------------+
| `<coordinate system>` | `::=`       | `<spatial cs> | <temporalCountMeasure cs> | <ordinal-dateTime cs>` |
+-----------------------+-------------+--------------------------------------------------------------------+
| `<spatial cs>`        | `::=`       | `<cs keyword> <left delimiter> <spatial cs type>`                  |
|                       |             |                                                                    |
|                       |             | `<wkt separator> <dimension>`                                      |
|                       |             |                                                                    |
|                       |             | `{(<wkt separator> <identifier>)}*`                                |
|                       |             |                                                                    |
|                       |             | `<right delimiter>`                                                |
|                       |             |                                                                    |
|                       |             | `(<wkt separator> <spatial axis>)*`                                |
|                       |             |                                                                    |
|                       |             | `{<wkt separator> <cs unit>}`                                      |
+-----------------------+-------------+--------------------------------------------------------------------+

## Система координат

Определяется рядом параметров:

+---------------------+----------+-------------------------------------------------------------------------------------------------------+
| `<dimension>`       | `::=`    | `1|2|3`                                                                                               |
+---------------------+----------+-------------------------------------------------------------------------------------------------------+
| `<spatial cs type>` | `::=`    | `affine | Cartesian | cylindrical | ellipsoidal | linear | parametric | polar | spherical | vertical` |
+---------------------+----------+-------------------------------------------------------------------------------------------------------+
| `<spatial axis>`    | `::=`    | `<axis keyword> <left delimiter> <axis nameAbbrev>`                                                   |
|                     |          |                                                                                                       |
|                     |          | `<wkt separator> <axis direction>`                                                                    |
|                     |          |                                                                                                       |
|                     |          | `{<wkt separator> <axis order>}`                                                                      |
|                     |          |                                                                                                       |
|                     |          | `{<wkt separator> <spatial unit>}`                                                                    |
|                     |          |                                                                                                       |
|                     |          | `{<wkt separator> <axis range>}`                                                                      |
|                     |          |                                                                                                       |
|                     |          | `{( <wkt separator> <identifier> )}*`                                                                 |
|                     |          |                                                                                                       |
|                     |          | `<right delimiter>`                                                                                   |
+---------------------+----------+-------------------------------------------------------------------------------------------------------+

## Типы систем координат

Аффинная

:   Координатная система в Евклидовом пространстве с прямыми осями, которые не обязательно взаимно перпендикулярны

    `CS[affine,2]`

Декартова

:   Аффинная система координат, в которой оси взаимно перепендикулярны и имеют одинаковые единицы измерения

    `CS[Cartesian,3]`

Линейная

:   Одномерная система координат, в которой ось определена линейным пространственным объектом

    `CS[linear,1]`

## Типы систем координат

Полярная

:   Двумерная система координат в Евклидовом пространстве, в котором местоположение определяется расстоянием и углом

    `CS[polar,2]`

Цилиндрическая

:   Трехмерная система координат в Евклидовом пространстве, в котором местоположение задается двумя расстояниями и углом

    `CS[cylindrical,3]`

Порядковая

:   Система координат, в которой местоположение по осям определяется целыми числами

    `CS[ordinal,2]`

## Типы систем координат

Сферическая

:   Двух- или трехмерная система координат в Евклидовом пространстве, в которой местоположение определяется двумя угловыми координатами и (в трехмерном случае) одной координатой-расстоянием

    `CS[spherical,3]`

Эллипсоидальная

:   Двух- или трехмерная система координат, в которой местоположение определяется геодезической широтой, долготой и (в трехмерном случае) геодезической высотой

    `CS[ellipsoidal,3]`

Параметрическая

:   Одномерная система координат, в которой единицы измерения по оси являются непространственными параметрами

    `CS[parametric,1]`

## Допустимые системы координат

+----------------------------------+-------------------+-------------------+
| **Координатная система отсчета** | **Допустимые СК** | **Размерность\    |
|                                  |                   | (число осей)**    |
+----------------------------------+-------------------+-------------------+
| геодезическая                    | декартова\        | 3\                |
|                                  | сферическая       | 2 или 3           |
+----------------------------------+-------------------+-------------------+
| географическая                   | эллипсоидальная   | 2 или 3           |
+----------------------------------+-------------------+-------------------+
| проецированная                   | декартова         | 2 или 3           |
+----------------------------------+-------------------+-------------------+
| проецированная *производная*     | аффинная\         | 2 или 3\          |
|                                  | декартова\        | 2 или 3\          |
|                                  | цилиндрическая\   | 3\                |
|                                  | порядковая\       | 1 или 2 или 3\    |
|                                  | полярная\         | 2\                |
|                                  | сферическая       | 2 или 3           |
+----------------------------------+-------------------+-------------------+

## Допустимые системы координат

+----------------------------------+-------------------+----------------+
| **Координатная система отсчета** | **Допустимые СК** | **Размерность\ |
|                                  |                   | (число осей)** |
+----------------------------------+-------------------+----------------+
| вертикальная                     | вертикальная      | 1              |
+----------------------------------+-------------------+----------------+
| инженерная                       | аффинная\         | 2 или 3\       |
|                                  | декартова\        | 2 или 3\       |
|                                  | цилиндрическая\   | 3\             |
|                                  | линейная\         | 1\             |
|                                  | порядковая\       | 1 или 2 или 3\ |
|                                  | полярная\         | 2\             |
|                                  | сферическая       | 2 или 3        |
+----------------------------------+-------------------+----------------+
| параметрическая                  | параметрическая   | 1              |
+----------------------------------+-------------------+----------------+
| временная                        | temporalDateTime\ | 1\             |
|                                  | temporalCount\    | 1\             |
|                                  | temporalMeasure   | 1              |
+----------------------------------+-------------------+----------------+

## Названия осей

Согласно стандарту [ISO 19111](https://www.iso.org/standard/74039.html), для каждой оси должны быть указаны как имя, так и аббревиатура. В стандарте [OGC 18-005r8](OGC%2018-005r8) требование более мягкое: достаточно указать одну или обе компоненты:

+--------------+--------------+------------------+
| `"northing"` | `"(Y)"`      | `"northing (Y)"` |
+--------------+--------------+------------------+

-   в **геоцентрической** СК указываются только аббревиатуры `(X)` , `(Y)`, `(Z)`

-   в **географической** СК указываются

    -   `geodetic latitude (Lat)`

    -   `geodetic longitude (lon)`

    -   `ellipsoidal height (h)`

-   в **проецированной** СК указываются

    -   `northing (N)` / `southing (S)`

    -   `easting (E)` / `westing (W)`

## Направления осей

Направление оси соответствует положительному изменению значания.

+--------------------------+----------------------------+-----------------------------------+
| **Координатная система** | **Допустимые направления** | **Пример**                        |
+--------------------------+----------------------------+-----------------------------------+
| географическая           | `north`, `east`, `up`      | `AXIS["(lat)",north]`\            |
|                          |                            | `AXIS["(lon)",east]`              |
+--------------------------+----------------------------+-----------------------------------+
| геодезическая декартова  | `geocentricX`\             | `AXIS["(X)",geocentricX]`\        |
|                          | `geocentricY`\             | `AXIS["(Y)",geocentricY]`\        |
|                          | `geocentricZ`              | `AXIS["(Z)",geocentricZ]`         |
+--------------------------+----------------------------+-----------------------------------+
| проецированная           | `north` / `south`\         | `AXIS["(E)",east]`\               |
|                          | `east` / `west`\           | `AXIS["(N)",north]`\              |
|                          | `up`                       | `AXIS["ellipsoid height (h)",up]` |
+--------------------------+----------------------------+-----------------------------------+
| вертикальная             | `up` / `down`              | `AXIS["depth (D)",down]`          |
+--------------------------+----------------------------+-----------------------------------+

## Порядок осей

Токен `<axis order> ::= ORDER[<digit>]` определяет соответствие между координатами точек в данных и осям координат.

-   Нумерация осей начинается с $1$ и увеличивается с шагом $1$

-   Порядок должен быть указан для всех осей, либо ни для какой из них

-   Если порядок не указан, по умолчанию предполагается, что порядок осей соответствует порядку их перечисления в описании СК.

Например, если в файле с данными координата $X$ соответствует направлению на север, то это можно указать в параметрах осей:

`AXIS["(E)", east,  ORDER[2]],`\
`AXIS["(N)", north, ORDER[1]]`

## Единицы измерения осей

Могут быть указаны как на уровне системы координат (`<cs unit>`), так и на уровне каждой оси по отдельности (`<axis unit>`).

::: callout-warning
## Внимание

Не следует использовать `<cs unit>` когда единицы измерения осей разные (например, в полярной СК).
:::

``` code
CS[Cartesian,3],
  AXIS["(X)",geocentricX], 
  AXIS["(Y)",geocentricY], 
  AXIS["(Z)",geocentricZ], 
  LENGTHUNIT["metre",1.0] — <cs unit>
  
CS[polar,2],
  AXIS["distance (r)", awayFrom, ORDER[1],
       LENGTHUNIT["metre",1.0]],                     — <axis unit>
  AXIS["bearing (U)", clockwise, BEARING[234], ORDER[2], 
       ANGLEUNIT["degree",0.0174532925199433]]       — <axis unit>
```

## Геодезические СК

**Топоцентрическая декартова**

``` code
CS[Cartesian,3], 
  AXIS["(X)",east],
  AXIS["(Y)",north],
  AXIS["(Z)",up], 
  LENGTHUNIT["metre",1.0]
```

**Геоцентрическая сферическая**

``` code
CS[spherical,2], 
  AXIS["geocentric latitude (U)",  north, ORDER[1], 
  AXIS["geocentric longitude (V)", east,  ORDER[2], 
  ANGLEUNIT["degree", 0.0174532925199433]
```

## Географические СК

**Трехмерная эллипсоидальная**

``` code
CS[ellipsoidal,3], 
  AXIS["latitude", north, ORDER[1],
    ANGLEUNIT["degree", 0.0174532925199433]], 
  AXIS["longitude", east, ORDER[2],
    ANGLEUNIT["degree", 0.0174532925199433]], 
  AXIS["ellipsoidal height (h)", up, ORDER[3],
    LENGTHUNIT["metre",1.0]]
```

**Двумерная эллипсоидальная**

``` code
CS[ellipsoidal,2], 
  AXIS["(lat)", north], 
  AXIS["(lon)", east], 
  ANGLEUNIT["degree", 0.0174532925199433]
```

## Проецированные СК

**Трехмерная**

``` code
CS[Cartesian,2],
  AXIS["northing (X)", north,ORDER[1]], 
  AXIS["easting (Y)", east,ORDER[2]], 
  AXIS["ellipsoid height (h)",up, ORDER[3]],
  LENGTHUNIT["metre",1.0]
```

**Двумерная с центром на полюсе**

``` code
CS[Cartesian,2],
  AXIS["easting (X)",south, 
    MERIDIAN[90,ANGLEUNIT["degree",0.0174532925199433]], ORDER[1]],
  AXIS["northing (Y)",south,
    MERIDIAN[180,ANGLEUNIT["degree",0.0174532925199433]], ORDER[2]],
  LENGTHUNIT["metre",1.0]
```

## Эллипсоид

**Эллипсоид** входит в состав исходных геодезических дат (датума)

+-----------------------+-------+---------------------------------------------------------------------------------------------------------------------------------+
| `<ellipsoid>`         | `::=` | `<ellipsoid keyword> <left delimiter> <ellipsoid name>  <wkt separator> <semi-major axis> <wkt separator> <inverse flattening>` |
|                       |       |                                                                                                                                 |
|                       |       | `{<wkt separator> <length unit>} {(<wkt separator> <identifier>)}* <right delimiter>`                                           |
+-----------------------+-------+---------------------------------------------------------------------------------------------------------------------------------+
| `<ellipsoid keyword>` | `::=` | `ELLIPSOID | SPHEROID`                                                                                                          |
+-----------------------+-------+---------------------------------------------------------------------------------------------------------------------------------+

``` code
ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1.0]]
SPHEROID["GRS 1980",6378137.0,298.257222101]
ELLIPSOID["Clark 1866",20925832.164,294.97869821, 
  LENGTHUNIT["US survey foot",0.304800609601219]]
ELLIPSOID["Sphere",6371000,0,LENGTHUNIT["metre",1.0]]
```

## Нулевой меридиан

**Нулевой меридиан** соответствует нулевому значению долготы

-   Относится к датуму, но не входит в его состав

-   Задается для геодезических и географических СК в случае если не совпадает с Гринвичским (*irm* --- international reference meridian)

+----------------------------+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| `<prime meridian>`         | `::=` | `<prime meridian keyword> <left delimiter> <prime meridian name> <wkt separator> <irm longitude> {(<wkt separator> <identifier>)}* <right delimiter>` |
+----------------------------+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| `<prime meridian keyword>` | `::=` | `PRIMEM | PRIMEMERIDIAN`                                                                                                                              |
+----------------------------+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------+

``` code
PRIMEM["Ferro",-17.6666667]
PRIMEM["Paris",2.5969213,ANGLEUNIT["grad",0.015707963267949]]
PRIMEMERIDIAN["Greenwich",0.0,ANGLEUNIT["degree",0.0174532925199433]]
```

## Библиография
