---
title: "Топологические отношения"
subtitle: "Геоинформатика I. Базы пространственных данных"
date: today
date-format: long
author: "Самсонов Тимофей Евгеньевич"
execute:
  echo: false
  freeze: true
engine: knitr
format:
  revealjs: 
    theme: [default, custom.scss]
    margin: 0.2
    width: 1280
    height: 720
    slide-number: true
    footer: "Самсонов Т. Е. Геоинформатика: курс лекций"
    header-includes: <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/pt-sans" type="text/css"/>
bibliography: references.yaml
mainfont: PT Sans
---

## История развития

Модели топологических отношений интенсивно развивались в первой половине 90-х гг. ХХ в.:

1.  Модель 4 пересечений **4IM** [@egenhofer1991].
2.  Модель 9 пересечений 9IM [@egenhofer1991a; @egenhofer1991b].
3.  Модель 4 пересечений с размерностью **DE-4IM** [@clementini1993].
4.  Аналитическая модель **CBM** [@clementini1993].
5.  Модель 9 пересечений с размерностью **DE-9IM** [@clementini1995].

::: callout-note
## DE-9IM

Модель DE-9IM описывает наиболее полный спектр топологических отношений и поддерживается в большинстве систем управления базами пространственных данных.
:::

## Обозначения

::: columns
::: {.column width="60%"}
| Символ             | Что означает               |
|--------------------|----------------------------|
| $P$                | точка                      |
| $L$                | линия                      |
| $A$                | полигон                    |
| $\lambda$          | $P|L|A$                    |
| $\partial$         | граница                    |
| $^\circ$           | внутренность               |
| $^-$               | внешняя область            |
| $\cap$             | пересечение                |
| $\varnothing$      | пустое множество           |
| $\neg \varnothing$ | непустое множество         |
| $\dim$             | топологическая размерность |
:::

::: {.column width="40%"}
**Топологические размерности**

$$
\begin{align}
\dim (P) &= 0 \\
\dim (L) &= 1 \\
\dim (A) &= 2 \\
\dim (\varnothing) &= -
\end{align}
$$

::: callout-note
## Нуль

Для обозначения отсутствия значения используется специальным символ --- нуль ($-$).
:::
:::
:::

## Библиография
