---
title: "Зачет"
author: "Тимофей Самсонов"
number-sections: true
date: last-modified
---

## Условия получения зачёта {.unnumbered}

Зачёт по курсу складывается из трёх компонент:

| №   | Компонента зачёта                                                               | Сроки проведения         | Кто оценивает                    |
|---------------|----------------------|------------------|------------------|
| 1   | Зачёты по практическим работам (включая контрольную работу в середине семестра) | В течение всего семестра | Преподаватель группы             |
| 2   | Итоговый практический зачёт                                                     | 24---29 апреля 2023 г.   | Преподаватель группы             |
| 3   | Итоговый теоретический зачёт                                                    | 2---3 мая 2023 г.        | Лектор и руководитель практикума |

Итоговый теоретический зачёт сдается в форме электронного теста в компьютерном классе. Теоретический зачёт считается сданным, если доля правильных ответов составляет не менее $60\%$.

Зачет по курсу проставляется при условии получения зачетов по всем трём компонентам.

## Вопросы для подготовки к теоретическому зачёту {.unnumbered}

### Географическая информация и пространственные данные {.unnumbered}

1.  Географическая информация
2.  Виды географической информации
3.  Пространственная привязка
4.  Геоинформатика
5.  Пространственный объект
6.  Информация
7.  Данные
8.  Пространственные данные
9.  Информационная система
10. Географическая информационная система (ГИС)
11. Геоинформатика (отрасль)
12. Концептуальная модель
13. Модель пространственных данных
14. Модели пространственных объектов
15. Объектно-ориентированная модель
16. Сетевая модель
17. Модель географических полей
18. Простой объект (векторный)
19. Сложный объект (покрытие)
20. Стандарт Simple Features (SF)
21. Линейная связность
22. Модели пространственных объектов SF
23. Хранение координат (WKT и WKB) в SF
24. Векторная модель и ее особенности
25. Модель покрытий
26. Топологическое покрытие и его элементы
27. Триангуляционное покрытие и его элементы
28. Растровое покрытие и его элементы
29. Диаграмма Вороного
30. Триангуляция Делоне
31. Сравнение растровой и триангуляционное модели
32. Геометрия растра
33. Пространственная привязка
34. Система координат (СК) и ее описание
35. Эллипсоид вращения
36. Исходные геодезические даты (датум)
37. Географическая система координат
38. Проекция
39. Плоская прямоугольная система координат
40. Форматы описания СК (WKT, PROJ.4, EPSG)
41. Операции с СК
42. Создание СК
43. Переопределение СК
44. Чтение СК
45. Преобразрвание СК
46. Преобразование координат
47. Трансформирование
48. Проецирование
49. Обратное проецирование
50. Координатная привязка (регистрация)
51. Опорные точки и принципы их выбора
52. Аффинное преобразование
53. Проективное преобразование
54. Полиномиальное преобразование
55. Преобразование методом резинового листа

### Создание объектов и пространственные отношения {.unnumbered}

1.  Автоматическое конструирование
2.  Геокодирование
3.  Географические идентификаторы
4.  Географический справочник (газеттир)
5.  Адресный локатор
6.  Геокодер
7.  Векторизация
8.  Автоматическая векторизация
9.  Автоматизированная векторизация
10. Ручная векторизация
11. Цифрование
12. Отношение
13. Пространственное отношение
14. Предикат
15. Метрические отношения
16. Евклидово расстояние
17. Манхэттенское расстояние
18. Геодезическое расстояние
19. Топологические отношения
20. Матрица Эгенхофера 9IM
21. Отношение НЕ ПЕРЕСЕКАЕТ (`DISJOINT`) и его матрица 9IM
22. Отношение РАВЕН (`EQUALS`) и его матрица 9IM
23. Отношение ПЕРЕКРЫВАЕТ (`OVERLAPS`) и его матрица 9IM
24. Отношение КАСАЕТСЯ (`TOUCHES`) и его матрица 9IM
25. Отношение ПОКРЫВАЕТ (`COVERS`) и его матрица 9IM
26. Отношение ПОКРЫТ (`COVERED`) и его матрица 9IM
27. Отношение СОДЕРЖИТ (`CONTAINS`) и его матрица 9IM
28. Отношение ВНУТРИ (`WITHIN`) и его матрица 9IM
29. Отношение ПЕРЕСЕКАЕТ и его связь с другими отношениями
30. Дирекционные отношения
31. Угловая модель
32. Прямоугольная модель
33. Проективная модель

### Базы пространственных данных {.unnumbered}

1.  База пространственных данных
2.  Модели баз данных и их сравнение
3.  Иерархическая модель
4.  Сетевая модель
5.  Реляционная модель
6.  Терминология реляционных БД
7.  Отношение
8.  Домен
9.  Атрибут
10. Кортеж
11. Ключ отношения и его свойства
12. Первичный ключ
13. Внешний ключ
14. Шкалы измерений
15. Номинальная шкала
16. Порядковая шкала
17. Интервальная шкала
18. Относительная шкала
19. Геореляционная база данных
20. Отношение геометрии и атрибутов
21. Опора измерений
22. Экстенсивные атрибуты
23. Интенсивные атрибуты
24. Уровни проектирования БД
25. Концептуальный уровень
26. Логический уровень
27. Физический уровень
28. Требования к базе данных
29. Система управления базами данных (СУБД)
30. Основные функции СУБД
31. Транзакции
32. Атрибутивные операции
33. Вычисление атрибутов
34. Интерполяция атрибутов
35. Классификация атрибутов
36. Агрегирование атрибутов
37. Фильтрация реляционных отношений
38. Проекция реляционных отношений
39. Соединение реляционных отношений
40. Язык SQL (Structured Query Language)
41. Запрос проекции `SELECT` на SQL
42. Оператор фильтрации `WHERE` на SQL
43. Оператор проверка на вхождение в множество `IN` на SQL
44. Иневртирование условия `NOT` в SQL
45. Проверка на пустоту `NOT NULL` в SQL
46. Вспомогательные операторы `LIKE`, `BETWEEN`, `GROUP BY` и `JOIN` в SQL
47. Пространственные запросы
48. Связь пространственных запросов с пространственным отношениями

### Векторный анализ {.unnumbered}

1.  Вычисление длины/перметра
2.  Вычисление площади
3.  Определение принадлежности точки полигону
4.  Ограничивающий прямоугольник
5.  Выпуклое множество
6.  Выпуклая оболочка
7.  Алгоритм Джарвиса для построения выпуклой оболочки
8.  Центроид фигуры и его вычисление
9.  Срединная ось фигуры
10. Буферная зона
11. Особенности буферных зон для точек, линий и полигонов
12. Взаимные преобразования моделей пространственных объектов
13. Взаимные преобразования обычных и мультиобъектов
14. Слияние (объединение по признаку)
15. Оверлей
16. Объединение
17. Пересечение
18. Разность
19. Симметрическая разность
20. Обрезка данных
21. Пространственная ассоциация
22. Односторонняя ассоциация
23. Двусторонняя ассоциация
24. Пространственные соотношения
25. Интерполяция взвешенная на площадь (ИВП)
26. ИВП для экстенсивных атрибутов
27. ИВП для интенсивных атрибутов

### Растровый анализ {.unnumbered}

1.  Растровая геометрия
2.  Регулярная геометрия
3.  Аффинная геометрия
4.  Ректилинейная геометрия
5.  Криволинейная геометрия
6.  Соотношение геометрии и матрицы данных
7.  Измерения растра
8.  Растровые кубы данных
9.  Изменение проекции растра
10. Трансформация растра
11. Деформация растра
12. Передискретизация растра и ее применение
13. Метод ближайшего соседа
14. Билинейная интерполяция
15. Растровая алгебра
16. Локальные операции и их применение
17. Фокальные операции и их применение
18. Окрестности фокальных операций
19. Свёртка
20. Сглаживание растра
21. Фокальные операции с нефиксированной окрестностью
22. Евклидово распределение
23. Евклидово расстояние
24. Зональные операции и их применение
25. Глобальные операции и их применение
26. Растровый оверлей
27. Взвешенный оверлей
28. Извлечение данных растра
29. Построение профиля по растру

### Цифровое моделирование рельефа {.unnumbered}

1.  Цифровая модель рельефа
2.  Покрытие
3.  Геоморфометрия
4.  Основные задачи геоморфометрии
5.  Аппроксимация поверхности
6.  Метод Эванса и его преимущество
7.  Производные поверхности Эванса
8.  Уклон и его выражение в производных
9.  Угол наклона и его связь с уклоном
10. Экспозиция склона и ее выражение в производных
11. Кривизна кривой
12. Плановая кривизна и ее интерпретация
13. Профильная кривизна и ее интерпретация
14. Интенсивность отражения света от поверхности
15. Модель Ламберта и ее математическое определение
16. Аналитическая отмывка
17. Отмывка при боковом освещении
18. Отмывка при отвесном освещении
19. Комбинация боковой и отвесной отмывки
20. Гидрологический анализ ЦМР
21. Основные задачи гидрологического анализа ЦМР
22. Предварительная подготовка ЦМР
23. Направление стока
24. Метод D8 и его формальное определение
25. Аккумуляция стока
26. Методы выражения аккумуляции стока
27. Вычисление аккумуляции в пикселе
28. Алгоритм построения растра аккумуляции стока
29. Потенциальные водотоки
30. Алгоритм выделения потенциальных водотоков
31. Управление густотой потенциальных водотоков через пороговое значение аккумуляции стока
32. Дренажный граф
33. Бассейн
34. Построение границы бассейна

### Пространственная интерполяция и вариография {.unnumbered}

1.  Пространственная статистика
2.  Моделирование пространственных распределений и его этапы
3.  Роль геостатистических методов
4.  Интерполяция в общем случае
5.  Детерминистические методы интерполяции
6.  Аналитическая функция и ее параметры
7.  Задача детерминистической интерполяции и ее формальная постановка
8.  Узлы интерполяции
9.  Метод ближайшего соседа
10. Интерполяция на основе триангуляции
11. Вычисление коээфициентов уравнения плоскости на основе триангуляции
12. Характерные особенности триангулированной поверхности
13. Метод обратно взвешенных расстояний (ОВР)
14. Весовая функция ОВР
15. Изменение вида поверхности ОВР при увеличении степени $\beta$
16. Характерная особенности поверхности, построенной методом ОВР
17. Радиальные базисные функции
18. Радиальная функция
19. Мультиквадрики
20. Обратные мультиквадрики
21. Мульти-логарифмическая функция
22. Сплайны минимальной кривизны
23. Влияние параметра $\delta$ на форму РБФ
24. Соотношение поверхности РБФ и диапазона исходных значений
25. Полиномиальная регрессия при разных степенях
26. Функция потери
27. Геостатистика
28. Вариограмма и ее математическое определение
29. Особенности вариограммы
30. Вариограммное облако и его интерпретация
31. Эмпирическая вариограмма и ее построение
32. Пространственный лаг
33. Интерпретация эмпирической вариограммы
34. Модель вариограммы и ее параметры
35. Эффект самородка
36. Радиус корреляции
37. Плато
38. Сферическая модель вариограммы
39. Экспоненциальная модель вариограммы
40. Гауссова модель вариограммы
41. Степенная модель вариограммы
42. Кригинг и его математическая постановка
43. Система уравнений обычного кригинга
44. Сумма весов обычного кригинга
45. Оценка кригинга
46. Дисперсия кригинга

### Пространственная зависимость и гетерогенность {.unnumbered}

1.  Пространственная зависимость
2.  Диаграмма рассеяния
3.  Линейная регрессия и ее формальная постановка
4.  Система линейных уравнений (СЛУ) регрессии
5.  Матричная форма СЛУ регрессии
6.  Остатки линейной регрессии
7.  Метод наименьших квадратов (МНК)
8.  Оптимальное решение СЛУ по МНК
9.  Модель линейно регрессии
10. Анализ карты остатков регрессии
11. Пространственная автокорреляция
12. Географическое соседство
13. Правило ферзя
14. Правило ладьи
15. Пространственные веса
16. Бинарные веса
17. Нормированные веса
18. Матрица весов W и ее вид для бинарного и нормированного случая
19. Коэффициент корреляции Пирсона
20. Индекс Морана и его формула
21. Интерпретация индекса Морана
22. Математическое ожидание индекса Морана
23. Автокорреляция остатков регрессии
24. Пространственная регрессия
25. Авторегрессия и ее коэффициент
26. Предикторы пространственной регрессии
27. Тренд
28. Сигнал
29. Шум
30. Выражение пространственной регрессии в виде обычной регрессии
31. Автокорреляция остатков пространственной регрессии
32. Пространственная гетерогенность
33. Географически взвешенная регрессия (ГВР)
34. Математическое определение ГВР
35. Весовая функция
36. Полоса пропускания и ее влияние на форму весовой функции
37. Фиксированная весовая функция
38. Адаптивная весовая функция
39. Коэффициенты ГВР
40. Карты коэффициентов ГВР и их интерпретация

### Модели размещения объектов {.unnumbered}

1.  Размещение географических объектов
2.  Точечный процесс
3.  Точечный паттерн
4.  Эталонные модели распределений
5.  Экспериментальный подход к анализу распределений
6.  Абсолютно случайное распределение (АСР)
7.  Распределение координат в АСР
8.  Ожидаемое количество точек в АСР
9.  Интенсивность точечного процесса
10. Распределение Пуассона
11. Выражение вероятности нахождения $k$ точек в заданной области
12. Однородный пуассоновский процесс
13. Симуляция однородного пуассоновскго процесса
14. Неоднородный пуассоновский процесс
15. Функция интенсивности неоднородного пуассоновского процесса
16. Ожидаемое количество точек в заданной области для неоднородного пуассоновского процесса
17. Процесс Кокса
18. Симуляция неодородного пуассоновского процесса методом Льюиса-Шедлера
19. Центробежная конфигурация точек
20. Центростремительная конфигурация точек
21. Кластерное распределение
22. Кластер
23. Моделирование кластерных распределений в три этапа
24. Кластерная модель Неймана-Скотта
25. Процесс Матерна
26. Процесс Томаса
27. Регулярное распределение
28. Расстояние ингибиции
29. Последовательная модель генерации регулярного распределения
30. Диагностика точечного распределения
31. Свойства I порядка
32. Свойства II порядка
33. Плотность пространственного распределения
34. Ядерное сглаживание
35. Диагностика плотности пространственного распределения
36. G-функция и ее формальное определение
37. Алгоритм применения G-функции
38. G-функция абсолютно случайного распределения
39. G-функция кластерного распределения
40. G-функция регулярного распределения
41. Анализ и моделирование размещения на примере неоднородного пуассоновского процесса

### Сетевой анализ {.unnumbered}

1.  Географические сети
2.  Граф и его формальное определение
3.  Элементы графа
4.  Матрица смежности
5.  Топологическая эквивалентность
6.  Направления сетевого анализа
7.  Подготовка данных для сетевого анализа
8.  Решение задач на графах
9.  Кратчайший маршрут
10. Особенности построения кратчайших маршрутов
11. Задача коммивояжёра и ее применение
12. Блажайший пункт обслуживания
13. Изохроны
14. Алгоритм построения изохрон
15. Анализ структуры географической сети
16. Центральность
17. Центральность по промежуточности
18. Центральность по близости
19. Центральность по степени
20. Центральность по влиятельности

### Геоинформационные технологии {.unnumbered}

*Вопросы по этому разделу будут опубликованы **28.04.2023**.*
