---
title: "Лекции"
author: 
  - name: "Тимофей Самсонов"
    orcid: 0000-0001-5994-0302
number-sections: true
date: last-modified
engine: knitr
---

::: callout-tip
## Как смотреть

Для просмотра презентации используйте стрелки навигации, либо щелкните на ней один раз *левой* кнопкой мыши и листайте стрелками на клавиатуре. Чтобы развернуть презентацию на весь экран, нажмите на клавиатуре клавишу <kbd>F</kbd>. Презентация должна быть открыта в отдельной вкладке браузера.
:::

::: callout-warning
## Если не отображаются диаграммы

Иногда на слайдах могут не отрисовываться диаграммы. В этом случае часть слайда или даже весь слайд будет выглядеть пустым. Чтобы исправить это, обновите страницу (<kbd>CTRL+R</kbd>). Презентация должна быть открыта в отдельной вкладке браузера.
:::

::: callout-note
## Как цитировать

Если вы использовали материалы лекций (например, иллюстрации) в своей работе, то необходимо оформить библиографическую ссылку в соответствии с [ГОСТ 7.0.108---2022](https://protect.gost.ru/document1.aspx?control=31&baseC=6&page=250&month=3&year=2014&search=ГОСТ&id=244975) следующим образом:

*Самсонов Т.Е.* **Основы геоинформатики: курс лекций** : сайт. 2025. --- URL: https://tsamsonov.github.io/gis-course/. Дата публикации: `r format(Sys.Date(), "%d.%m.%Y")`. DOI: 10.5281/zenodo.7902351
:::

## Географическая информация

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/01_Geoinformation.html" title="Лекция №1. Географическая информация и пространственные данные"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Модели пространственных данных

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/02_Models.html" title="Лекция №1. Географическая информация и пространственные данные"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Пространственная привязка и создание объектов

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №2. Пространственная привязка и создание объектов"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Базы пространственных данных

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №3. Базы пространственных данных"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Векторный анализ

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №4. Векторный анализ"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Растровый анализ

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №5. Растровый анализ"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Сетевой анализ

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №6. Сетевой анализ"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Цифровое моделирование рельефа и геоморфометрия

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №7. Цифровое моделирование рельефа и геоморфометрия"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Пространственная интерполяция и вариография

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №8. Пространственная интерполяция и вариография"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Пространственная и географически взвешенная регрессия

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №9. Пространственная и географически взвешенная регрессия"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Точечные процессы

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №10. Точечные процессы"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.

## Геоинформационные технологии

::: {style="position: relative; overflow: hidden; width: 100%; padding-top: 56.25%;"}
```{=html}
<iframe style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%;" src="https://tsamsonov.github.io/gis-course/coming-soon.html" title="Лекция №11. Геоинформационные технологии"></iframe>
```
:::

[**Открыть**](https://tsamsonov.github.io/gis-course/coming-soon.html){target="_blank"} в отдельной вкладке браузера.
